# Generated by Django 5.2.1 on 2025-06-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("last_destination", models.CharField(blank=True, max_length=100)),
                ("preferences", models.TextField(blank=True)),
            ],
        ),
    ]
