# Generated by Django 5.2.1 on 2025-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_travelerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelerprofile",
            name="travel_buddy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="travelerprofile",
            name="travel_style",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
