# Generated by Django 5.2.1 on 2025-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_itinerary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelerprofile",
            name="phone_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
