# Generated by Django 5.2.1 on 2025-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_alter_travelerprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
