# Generated by Django 5.2.1 on 2025-12-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_alter_itinerary_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="user_id",
            new_name="user",
        ),
    ]
