# Generated by Django 5.2.1 on 2025-12-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_rename_user_id_chathistory_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="user",
            new_name="phone_number",
        ),
    ]
